### ISSUE TITLE
Pulumi Github app does not show the diff

### ISSUE THREAD

**Issue by Olsenius** [pulumi/pulumi-cloud-requests#120]
### What happened?

The Pulumi github app does not show the diff like the github action does with `comment-on-pr: true` and `diff: true`. 

Is there a way to fix this?

### Steps to reproduce

```yaml
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: scaleaq/prod
          refresh: true
          diff: true
          pulumi-version: v3.19.0
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

### Expected Behavior

Pulumi github app should include the diff as the github actions comment does. 

### Actual Behavior

![image](https://user-images.githubusercontent.com/198483/192970276-67e4042f-118f-4bd7-a5ad-55f0a09674a8.png)

### Additional context

`pulumi-version: v3.19.0` is set to get the diff ref: https://github.com/pulumi/actions/issues/731#issuecomment-1261181584 

Original question on [Slack](https://pulumi-community.slack.com/archives/C84L4E3N1/p1664435055916279)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
