### ISSUE TITLE
Configure deployments with organizational templates to be used with the NPW

### ISSUE THREAD

**Issue by stooj** [pulumi/pulumi-cloud-requests#499]
Allow organizational templates to configure deployment settings for stacks, so the NPW can automatically include org-specific deployment config.

## Affected feature

- New Project Wizard (NPW)
- Organizational Templates
- Deployments

Companies often have custom (but repeatable) deployment configuration.

Say they have a private repo, they would need to include an SSH key and some `pre-run` commands to get it configured properly.

Including these setup steps as part of a template that could be run from the NPW would go a long way towards a "no code" experience.

The deployment configuration could be included in the `Pulumi.yaml` file in the template, or perhaps a `Pulumi.deployment.yaml` file. Something that could be included in the template repo.

Example of what that might look like:

```yaml
deploymentSettings:
  sourceContext:
    git:
      repository: ${REPO}
      deployCommits: true
      previewPullRequests: true
  operationContext:
    preRunCommands: 
      - mkdir /root/.ssh && printf -- "$SSHKEY" > /root/.ssh/id_ed25519
      - chmod 600 /root/.ssh/id_ed25519
      - yarn
    environmentVariables:
      SSH_KEY: ssh-probably-should-not-live-in-the-template-repo

```
