### ISSUE TITLE
[ESC] Allow importing whole stack outputs as part of the `import` statement

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-cloud-requests#509]
Pulumi ESC is great at **seamlessly** exposing configurations to Pulumi app whether it be configuration, secrets, external secrets, hardcoded values and of course stack references. As ESC acts the cornerstone of configuration management in Pulumi, more and more users are using Pulumi ESC to centralize their configuration for both new infra project and **legacy ones**. Thus creating some kind of migration pattern where they can get moving by just copy/pasting values of known infra and consume them as a Pulumi config.

This might become somewhat limiting when a user has many stack references stored in ESC because it would be quite verbose and ESC document could be either large or too many.

```yaml
values:
  network:
    fn::open::pulumi-stacks:
      stacks:
        core-network:
          stack: core-network/dev
  app:
    fn::open::pulumi-stacks:
      stacks:
        k8-cluster:
          stack: k8-cluster-1/dev
  pulumiconfig:
    clusterVpcID: ${network.core-network.vpcId}
    clustersubnetID: ${network.core-network.subnetId}
    kubeConfig: ${app.k8-cluster.kubeconfig}
```

or as a shorter syntax

```yaml
values:
  outputs:
    fn::open::pulumi-stacks:
      stacks:
        core-network:
          stack: core-network/dev
        k8-cluster:
          stack: k8-cluster-1/dev
  pulumiconfig:
    clusterVpcID: ${outputs.core-network.vpcId}
    clustersubnetID: ${outputs.core-network.subnetId}
    kubeConfig: ${outputs.k8-cluster.kubeconfig}
```

To assist with this, we could extend the ESC syntax to **import** the stack outputs as **values**.

```yaml
imports:
  environments:
    - cloud-access
  stacks:
    - core-network/dev
    - k8-cluster-1/dev
```

## Note

This issue has been added to our internal tracker, for additional context, check the relevant thread.

## Affected feature

- Pulumi ESC

**Comment by zacdirect** [comment]
I imagine there's good discussion to be had around if all outputs automatically express as raw values, environment variables, or pulumiConfigs.  I have a current use-case that only needs them as pulumiConfigs on a 1:1 no transformation basis, but I could see others wanting to express runtime/config/value/all somehow.
 
Another thing to note is that ESC currently doesn't support 3 part imports.  That could be a way of importing stacks without having to nest environments vs stacks.  E.g.
 
 ```yaml
 imports:
     - project/cloud-access
     - org/core-network/dev
     - org/k8-cluster-1/dev
 ```
 
You can see the difference of stacks vs env because stacks have 3-part names.  
 
No real preferences from me, just calling out some discussion points that could possibly inform an implementation.

**Comment by komalali** [comment]
@aureq not denying the value of your suggestion, but I did want to point out that your example is more verbose than it needs to be. 

This:
```
values:
  network:
    fn::open::pulumi-stacks:
      stacks:
        core-network:
          stack: core-network/dev
  app:
    fn::open::pulumi-stacks:
      stacks:
        k8-cluster:
          stack: k8-cluster-1/dev
  pulumiconfig:
    clusterVpcID: ${network.core-network.vpcId}
    clustersubnetID: ${network.core-network.subnetId}
    kubeConfig: ${app.k8-cluster.kubeconfig}
```

Could be this:
```
values:
  outputs:
    fn::open::pulumi-stacks:
      stacks:
        core-network:
          stack: core-network/dev
        k8-cluster:
          stack: k8-cluster-1/dev
  pulumiconfig:
    clusterVpcID: ${outputs.core-network.vpcId}
    clustersubnetID: ${outputs.core-network.subnetId}
    kubeConfig: ${outputs.k8-cluster.kubeconfig}
```
