### ISSUE TITLE
Deployments: Support for centralized config/dynamic credentials (ESC/Deployments integration)

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-cloud-requests#512]
I'm seeing some key friction points for larger orgs who want to adopt Deployments at scale:

* Deployment settings must be duplicated on a per-stack basis. The Pulumi Cloud IaC provider is an ok solution, but centralized, versioned config for Deployments that can be applied to many stacks at once would significantly reduce duplication, make rollouts easier, etc.
* Some image repos require short-lived credentials (I believe ECR has this requirement). Deployments lacks the ability to hand dynamic credentials, so this use case is basically impossible for orgs who want to use private custom runner images in ECR.
* Cloning private git repos with temporary (or at least rotate-able) credentials is rough or impossible today. Azure DevOps uses personal access tokens which have a limited maximum life.
* Pre-run commands that require credentials are painful (but each line can be wrapped in `pulumi env run`, so it's at least possible).

Being able to apply ESC to Deployments in a centralized, versioned manner would be an elegant solution to this problem. I'm thinking something like this:

```yaml
values:
  aws:
    dev:
      # aws-login provider stuff
      # aws-ecr provider stuff, which does not exist as I write this (would get temporary credentials for ECR)
  pulumiConfig:
    # etc...
  pulumiDeployments: # <-- well-known config value
    # what follows should roughly follow the structure of the DeploymentSettings resource/object
    executorContext:
      executorImage:
        reference: something.something.ecr.amazonaws.com/something/something:latest
        credentials: ${aws.dev.ecr.token}
```

Very open to other implementations - this is just what I first thought of.
